[pytest]
# Diretório onde o pytest vai procurar os testes por padrão
testpaths = tests

# Padrão de nomenclatura que o pytest vai reconhecer
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Flags padrão:
# -v para modo verboso (mostra o nome de cada teste que passou ou falhou)
# --disable-warnings para esconder avisos de dependências de terceiros e focar nos seus erros
addopts = -v --disable-warnings

# Se for usar chamadas assíncronas (async def) nos testes do FastAPI,
# lembre-se de instalar o pytest-asyncio e descomentar a linha abaixo:
# asyncio_mode = auto
